name: Generate SBOM

on:
  push:
    branches:
      - main # De workflow draait automatisch bij pushes naar de main branch
  workflow_dispatch: {} # Dit voegt de "Run workflow" knop toe in de GitHub UI

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Gebruik een geschikte Node.js versie voor Juice Shop

      - name: Install dependencies
        run: npm install

      # DEZE STAP VERWIJDEREN OF UITCOMMENTARIËREN:
      # - name: Install CycloneDX CLI
      #   run: npm install -g @cyclonedx/bom 

      - name: Generate SBOM # <-- HIER IS DE BELANGRIJKE WIJZIGING
        run: npx @cyclonedx/cyclonedx-npm --output-file sbom.json
        # Het commando 'cyclonedx-cli scan --input-file package.json ...' is niet nodig/correct meer.
        # 'npx @cyclonedx/cyclonedx-npm' leest automatisch package.json en genereert een SBOM.

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
